// Copyright (C) Microsoft Corporation. All rights reserved.
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Build.Extras.FX1_1.UnitTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestFailureStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestFailureStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Build.Extras.FX1_1.UnitTests.TestFailureStrings", typeof(TestFailureStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegistryKey: {0} exists. Change to a different, non-existent key..
        /// </summary>
        internal static string BadRegistryKeyExists {
            get {
                return ResourceManager.GetString("BadRegistryKeyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegistryKey: {0} exists under {1}. Change the base key so {0} doesn&apos;t reside under it..
        /// </summary>
        internal static string ChangeBaseKey {
            get {
                return ResourceManager.GetString("ChangeBaseKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConvertItemMetadataToString should have returned an empty string..
        /// </summary>
        internal static string ConvertMetadataToStringReturnedNonEmptyString {
            get {
                return ResourceManager.GetString("ConvertMetadataToStringReturnedNonEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CopyReferences should have succeeded and thus returned true..
        /// </summary>
        internal static string CopyReferencesFailed {
            get {
                return ResourceManager.GetString("CopyReferencesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CopyReferences should return true when no references are specified..
        /// </summary>
        internal static string CopyReferencesReturnedFalseWithNoRefs {
            get {
                return ResourceManager.GetString("CopyReferencesReturnedFalseWithNoRefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CopyResGen should have succeeded and thus returned true..
        /// </summary>
        internal static string CopyResGenFailed {
            get {
                return ResourceManager.GetString("CopyResGenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSBee.GenerateResource.CreateOutputResourcesNames returned false instead of true..
        /// </summary>
        internal static string CreateOutputResourceNamesReturnedFalse {
            get {
                return ResourceManager.GetString("CreateOutputResourceNamesReturnedFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateUniqueTempDirectory failed..
        /// </summary>
        internal static string CreateUniqueTempDirectoryFailed {
            get {
                return ResourceManager.GetString("CreateUniqueTempDirectoryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteTempResGenPath should have succeeded and thus returned true..
        /// </summary>
        internal static string DeleteTempResGenPathFailed {
            get {
                return ResourceManager.GetString("DeleteTempResGenPathFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value {0} is not found under this key. Review the registry entry to confirm this assertion..
        /// </summary>
        internal static string ExpectedRegistryValuesNotPresent {
            get {
                return ResourceManager.GetString("ExpectedRegistryValuesNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} doesn&apos;t exist..
        /// </summary>
        internal static string FileDoesntExist {
            get {
                return ResourceManager.GetString("FileDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was not copied to {1}..
        /// </summary>
        internal static string FileNotCopied {
            get {
                return ResourceManager.GetString("FileNotCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should have been created but it doesn&apos;t exist..
        /// </summary>
        internal static string FileShouldExist {
            get {
                return ResourceManager.GetString("FileShouldExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenerateResource.Execute returned false..
        /// </summary>
        internal static string GenerateResourceReturnedFalse {
            get {
                return ResourceManager.GetString("GenerateResourceReturnedFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test is ignored because user does not have enough permission to view/modify registry..
        /// </summary>
        internal static string GetSearchPathIgnoredDueToPermissions {
            get {
                return ResourceManager.GetString("GetSearchPathIgnoredDueToPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test is ignored because registry key is present on the system..
        /// </summary>
        internal static string GetSearchPathIgnoredKeyPresent {
            get {
                return ResourceManager.GetString("GetSearchPathIgnoredKeyPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expected ItemSpec for the task is {0} but the actual ItemSpec is {1}..
        /// </summary>
        internal static string ItemSpecValuesArentEqual {
            get {
                return ResourceManager.GetString("ItemSpecValuesArentEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The metadata array must have an odd length for this test..
        /// </summary>
        internal static string MetadataLengthIsEven {
            get {
                return ResourceManager.GetString("MetadataLengthIsEven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expected value for {0} is &quot;{1}&quot; but the actual value is &quot;{2}&quot;..
        /// </summary>
        internal static string MetadataValuesArentEqual {
            get {
                return ResourceManager.GetString("MetadataValuesArentEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of the provided references are read-only references..
        /// </summary>
        internal static string NoReadOnlyReferences {
            get {
                return ResourceManager.GetString("NoReadOnlyReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of outputResources should be {0} but instead is {1}..
        /// </summary>
        internal static string OutputResourcesHasUnexpectedLength {
            get {
                return ResourceManager.GetString("OutputResourcesHasUnexpectedLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} doesn&apos;t end with a path separator..
        /// </summary>
        internal static string PathDoesntEndWithSeparator {
            get {
                return ResourceManager.GetString("PathDoesntEndWithSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegistryKey: {0} doesn&apos;t exist. Change to a key that exists..
        /// </summary>
        internal static string RegistryKeyDoesntExist {
            get {
                return ResourceManager.GetString("RegistryKeyDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The registryKey should have values beneath it but the list of values has {0} entries..
        /// </summary>
        internal static string RegistryKeyMissingValues {
            get {
                return ResourceManager.GetString("RegistryKeyMissingValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetItemMetadata should have returned null..
        /// </summary>
        internal static string SetItemMetadataReturnedNonNull {
            get {
                return ResourceManager.GetString("SetItemMetadataReturnedNonNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} returned false..
        /// </summary>
        internal static string TaskFailed {
            get {
                return ResourceManager.GetString("TaskFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string representation of the TaskItem contains {0} even though it has an empty value..
        /// </summary>
        internal static string TaskItemStringContainsEmptyValue {
            get {
                return ResourceManager.GetString("TaskItemStringContainsEmptyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string representation of the TaskItem is missing the string {0}..
        /// </summary>
        internal static string TaskItemStringIsMissing {
            get {
                return ResourceManager.GetString("TaskItemStringIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The temp directory wasn&apos;t created..
        /// </summary>
        internal static string TempDirectoryNotCreated {
            get {
                return ResourceManager.GetString("TempDirectoryNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should have been deleted by DeleteTempResGenPath but still exists..
        /// </summary>
        internal static string TempResGenDirectoryStillExists {
            get {
                return ResourceManager.GetString("TempResGenDirectoryStillExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSBee.GenerateResource.ToolName was set to {0} instead of {1}..
        /// </summary>
        internal static string ToolNameIsIncorrect {
            get {
                return ResourceManager.GetString("ToolNameIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No values for registry key {0} should be present at depth {1}..
        /// </summary>
        internal static string UnexpectedRegistryValuesPresent {
            get {
                return ResourceManager.GetString("UnexpectedRegistryValuesPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sample output file contains an unexpected resolvedFile entry with its ItemSpec set to {0}..
        /// </summary>
        internal static string UnexpectedResolvedFileEntry {
            get {
                return ResourceManager.GetString("UnexpectedResolvedFileEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetBaseRegistryKey returned {0} as the base key, instead of returning {1}..
        /// </summary>
        internal static string WrongBaseKeyReturned {
            get {
                return ResourceManager.GetString("WrongBaseKeyReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Framework path is expected to be {0} but the task returned {1} as the path..
        /// </summary>
        internal static string WrongFrameworkPath {
            get {
                return ResourceManager.GetString("WrongFrameworkPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Framework SDK path is expected to be {0} but the task returned {1} as the path..
        /// </summary>
        internal static string WrongFrameworkSDKPath {
            get {
                return ResourceManager.GetString("WrongFrameworkSDKPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expected resource name for {0} is {1} but {2} was generated instead.
        ///.
        /// </summary>
        internal static string WrongResourceNameWasGenerated {
            get {
                return ResourceManager.GetString("WrongResourceNameWasGenerated", resourceCulture);
            }
        }
    }
}
