// Copyright (C) Microsoft Corporation. All rights reserved.
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.32
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Build.Extras.FX1_1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Build.Extras.FX1_1.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The temp output file was not created due to &quot;{0}&quot; {1}..
        /// </summary>
        internal static string CreatingTempFileFailed {
            get {
                return ResourceManager.GetString("CreatingTempFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutputResources does not have one file name for each name in sources. Creating default file names for OutputResources..
        /// </summary>
        internal static string DefaultOutputResources {
            get {
                return ResourceManager.GetString("DefaultOutputResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting file &quot;{0}&quot;..
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting directory &quot;{0}&quot;..
        /// </summary>
        internal static string DeleteDirectory {
            get {
                return ResourceManager.GetString("DeleteDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task failed to delete &quot;{0}&quot;..
        /// </summary>
        internal static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access was denied to &quot;{0}&quot;; will re-attempt deletion..
        /// </summary>
        internal static string DeleteFailedWillRetry {
            get {
                return ResourceManager.GetString("DeleteFailedWillRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task failed to delete &quot;{0}&quot; due to &quot;{1}&quot;{2}.
        /// </summary>
        internal static string DeleteFailedWithException {
            get {
                return ResourceManager.GetString("DeleteFailedWithException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task failed while creating a directory due to &quot;{0}&quot;{1}.
        /// </summary>
        internal static string DirectoryCreationFailed {
            get {
                return ResourceManager.GetString("DirectoryCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying file from &quot;{0}&quot; to &quot;{1}&quot;..
        /// </summary>
        internal static string FileCopy {
            get {
                return ResourceManager.GetString("FileCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task failed to copy &quot;{0}&quot; to &quot;{1}&quot; due to &quot;{2}&quot;{3}.
        /// </summary>
        internal static string FileCopyFailed {
            get {
                return ResourceManager.GetString("FileCopyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The response file &quot;{0}&quot; could not be processed due to &quot;{1}&quot; {2}..
        /// </summary>
        internal static string FileReadFailed {
            get {
                return ResourceManager.GetString("FileReadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An incorrect number of metadata elements, {0}, were retrieved for this TaskItem..
        /// </summary>
        internal static string IncorrectNumberOfMetadata {
            get {
                return ResourceManager.GetString("IncorrectNumberOfMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource file &quot;{0}&quot; has an invalid name. {1}.
        /// </summary>
        internal static string InvalidFileName {
            get {
                return ResourceManager.GetString("InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The .NET Framework v1.1 is not installed..
        /// </summary>
        internal static string NETFrameworkNotFound {
            get {
                return ResourceManager.GetString("NETFrameworkNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The .NET Framework SDK v1.1 is not installed. .
        /// </summary>
        internal static string NETFrameworkSDKNotFound {
            get {
                return ResourceManager.GetString("NETFrameworkSDKNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The RegistryKey property must be set..
        /// </summary>
        internal static string NoRegistryKey {
            get {
                return ResourceManager.GetString("NoRegistryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No resources specified in &quot;Sources&quot;. Skipping resource generation..
        /// </summary>
        internal static string NoSources {
            get {
                return ResourceManager.GetString("NoSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} parameter was null..
        /// </summary>
        internal static string NullParameter {
            get {
                return ResourceManager.GetString("NullParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} output file, &quot;{1}&quot;, does not exist..
        /// </summary>
        internal static string OutputFileDoesNotExist {
            get {
                return ResourceManager.GetString("OutputFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output file &quot;{0}&quot; was not processed successfully (and may not have been deleted) due to &quot;{1}&quot; {2}..
        /// </summary>
        internal static string OutputFileFailedProcessing {
            get {
                return ResourceManager.GetString("OutputFileFailedProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output file contains an unexpected switch: {0}..
        /// </summary>
        internal static string OutputFileHasUnexpectedSwitch {
            get {
                return ResourceManager.GetString("OutputFileHasUnexpectedSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task failed because &quot;{0}&quot; was not found, or the .NET Framework SDK {1} is not installed.  The task is looking for &quot;{0}&quot; in the &quot;bin&quot; subdirectory beneath the location specified in the {2} value of the registry key {3}.  You may be able to solve the problem by doing one of the following:  1.) Install the .NET Framework SDK {1}.  2.) Manually set the above registry key to the correct location.  3.) Pass the correct location into the &quot;ToolPath&quot; parameter of the task.
        ///.
        /// </summary>
        internal static string PlatformSDKFileNotFound {
            get {
                return ResourceManager.GetString("PlatformSDKFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The RegEx object was unable to successfully process the output file &quot;{0}&quot;..
        /// </summary>
        internal static string RegExFailedToMatch {
            get {
                return ResourceManager.GetString("RegExFailedToMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; does not exist in the local machine&apos;s registry..
        /// </summary>
        internal static string RegistryKeyNotFound {
            get {
                return ResourceManager.GetString("RegistryKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; failed and returned {1}.
        ///.
        /// </summary>
        internal static string ToolFailed {
            get {
                return ResourceManager.GetString("ToolFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tool path could not be generated due to &quot;{0}&quot; {1}..
        /// </summary>
        internal static string ToolPathGenerationFailed {
            get {
                return ResourceManager.GetString("ToolPathGenerationFailed", resourceCulture);
            }
        }
    }
}
